/*
 * Copyright (C) 2019-2021 HERE Europe B.V.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * SPDX-License-Identifier: Apache-2.0
 * License-Filename: LICENSE
 */

import {Feature} from '@here/xyz-maps-core';

let UNDEF;

/**
 *  Map Event
 */
class MapEvent {
    /**
     * The underlying native Mouse-, Pointer- or Touch-event generated by the browser.
     * This property will be null if the Event was not directly generated from a native event.
     */
    nativeEvent?: MouseEvent|TouchEvent|PointerEvent|null;
    /**
     *  The type of the event.
     *  Supported events: 'mapviewchangestart', 'mapviewchange', 'mapviewchangeend', 'resize',
     * 'tap', 'dbltap', 'pointerup', 'pointerenter', 'pointerleave', 'pointerdown', 'pointermove', 'pressmove'
     */
    type: string;
    /**
     *  This property specifies the time at which the event was created in milliseconds relative to 1970-01-01T00:00:00Z.
     */
    timeStamp: DOMTimeStamp;
    /**
     *  The map feature this event relates to.
     */
    target?: Feature|null;
    /**
     *  This property holds the numeric id of a mouse button that has changed state, because it was pressed or released.
     */
    button?: number;
    /**
     *  Gives the x coordinate relative to the map container HTMLElement in pixels
     */
    mapX?: number;
    /**
     *  Gives the y coordinate relative to the map container HTMLElement in pixels
     */
    mapY?: number;

    constructor(type: string, detail?: any) {
        this.type = type;
        this.timeStamp = Date.now();

        if (detail != UNDEF) {
            this.data =
                this.detail = detail;
        }
    }

    stopPropagation() {
        const ev = this.nativeEvent;
        // make sure move are not received by map pan handler in any case..
        if (ev.type == 'mousemove' || ev.type == 'touchmove') {
            ev.stopImmediatePropagation();
            // disable's (ios)browser's  "page-scroll"/"pinch to zoom"...
            return ev.preventDefault();
        }
        // up/down events need to pass..
        // return ev.stopPropagation()
    };

    toString() {
        return 'MapEvent ' + this.type;
    };
    /**
    * optional event detail data
    */
    detail?: any;
    data: any;
}


export {MapEvent};
