name: Docs & Playground

on:
    workflow_dispatch:

env:
    yarn-network-timeout: 1000000

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2
            -   name: Get yarn cache directory path
                id: yarn-cache-dir-path
                run: echo "::set-output name=dir::$(yarn cache dir)"
            -   uses: actions/cache@v4
                id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
                with:
                    path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
                    key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
                    restore-keys: |
                        ${{ runner.os }}-yarn-
            -   name: Setup Node.js
                uses: actions/setup-node@v2
                with:
                    node-version: '20'
            -   name: Install dependencies
                run: yarn install --network-timeout ${{ env.yarn-network-timeout }}
            -   name: Build documentation
                run: yarn run build-doc
            -   name: Build release
                run: yarn run build-release
            -   name: Build playgorund
                run: yarn run build-playground -- -- --environment BUILD:production --environment doc-path:../docs/ --environment api-path:../ --environment token-path:${{ secrets.TOKEN_PATH }}
            -   name: Preapre deployment
                run: node scripts/prepare-pages.js
            -   name: Deploy to gh-pages
                uses: peaceiris/actions-gh-pages@v3
                with:
                    github_token: ${{ secrets.GITHUB_TOKEN }}
                    publish_dir: ./deploy
                    force_orphan: true
